<?php include('header.php') ?>
<?php include('parts/banner.php') ?>
<?php include('parts/pickupform.php') ?>
<?php include('parts/searchbooking.php') ?>
<?php include('parts/about.php') ?>
<?php include('parts/ourservices.php') ?>
<?php include('parts/CarRental.php') ?>
<?php include('parts/howitworks.php') ?>
<?php include('parts/whychooseus.php') ?>
<?php include('parts/Testimonial.php') ?>
<?php include('parts/gallery.php') ?>
<?php include('footer.php') ?>
